# Keratoconus high-contrast Gruvbox p10k overrides.
# Sourced from the END of ~/.zshrc (after ~/.p10k.zsh) so these values win.
POWERLEVEL9K_DIR_FOREGROUND='#83a598'            # bright blue
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#fabd2f'     # bright yellow — anchors pop
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#928374'  # gray
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#b8bb26'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#b8bb26'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#fb4934'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND='#fb4934'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#b8bb26'      # green
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#fabd2f'   # yellow
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#8ec07c'  # cyan — distinct from clean green
POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#fb4934'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#fb4934'
POWERLEVEL9K_AWS_FOREGROUND='#fe8019'            # orange
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='#d3869b'    # magenta
